---

- hosts: servers-chain-THA-master servers-chain-THA-slaves
  gather_facts: False
  any_errors_fatal: true
  become: yes
  become_user: user1
  become_method: su
  vars:
    home_work_dir: /home/user1/me-deploy
    hosts_name: servers-chain-THA-master servers-chain-THA-slaves
    master_group: servers-chain-THA-master
    slaves_group: servers-chain-THA-slaves
    node_count: 7
    has_root_pwd: false
    master_node_host_ip: 192.168.87.2
    validator_begin_node_pos: 1
    validator_end_node_pos: 35
  roles:
    - chain