---

- hosts: servers-chain-test servers-chain-test
  gather_facts: False
  any_errors_fatal: true
  become: yes
  become_user: meuser
  become_method: su
  vars:
    home_work_dir: ~/me-deploy
    chain_bin_file_dir: ~/me-deploy
    hosts_name: servers-chain-test servers-chain-test
    master_group: servers-chain-test
    slaves_group: servers-chain-test
    node_count: 7
    has_root_pwd: false
    master_node_host_ip: 192.168.0.207
    validator_begin_node_pos: 1
    validator_end_node_pos: 7
    common:
      chain_bin_name: me-chaind
      coin_unit: mec
      admin_name: admin
      explorer_backend_bin_name: me-explorer
      chain_id: mechain
      keyring_dir: me-chain
      keyring_backend: test
      minimum_gas_prices: 200

  roles:
    - nyl1001.xd_me