---

- hosts: servers-chain-THA-master servers-chain-THA-slaves
  gather_facts: False
  any_errors_fatal: true
  become: yes
  become_user: user1
  become_method: su
  vars:
    home_work_dir: /home/user1/me-deploy
    chain_bin_file_dir: ~/me-deploy
    hosts_name: servers-chain-THA-master servers-chain-THA-slaves
    master_group: servers-chain-THA-master
    slaves_group: servers-chain-THA-slaves
    node_count: 7
    has_root_pwd: false
    master_node_host_ip: 192.168.87.2
    validator_begin_node_pos: 1
    validator_end_node_pos: 35
    common:
      chain_bin_name: me-chaind
      coin_unit: mec
      admin_name: admin
      explorer_backend_bin_name: me-explorer
      chain_id: mechain
      keyring_dir: me-chain
      keyring_backend: test
      minimum_gas_prices: 200
  roles:
    - nyl1001.xd_me